update

diff --git a/prntl b/prntl
--- a/prntl
+++ b/prntl
@@ -1,5 +1,7 @@
 #!/usr/bin/env bash
 
+prntl_version=0.4
+
 LOG_FILE=prntl.log
 TIME_FORMAT='%d %b %Y %T %z'
 LOG_FORMAT='%time - %log'
@@ -8,23 +10,39 @@ prntl_print_help() {
 cat << EOF
 Print formatted log to STDOUT and log file.
 
-Usage:
-    prntl [OPTIONS]... [ARGUMENTS]...
+Usage: prntl [-v| --version] [-h | --help] [-o | --output=<file>]
+             [-f | --log-format=<string>] [-t | --time-format=<string>]
+             [-p | --no-print] [-c | --no-color]
 
 Options:
-    -o, --output        set log file name. Default: printl.log.
-    -f, --log-format    set log format. Formatting options:
-                            %time   time; see '--time-format'.
-                            %log    log string.
-                        Example: prntl -f 'mylog %time : %log'
-    -t, --time-format   set time format; see 'date --help'
-                        or 'man date' for details.
-                        Example: prntl -t '%D %T'
-    -c, --no-color      remove ANSI color codes from log string.
-    -p, --no-print      don't print log to STDOUT.
-    -h, --help          show this help message and exit.
+    -o, --output=<file>         set log file name. Default: $LOG_FILE.
+    -f, --log-format=<string>   set log format. Formatting options:
+        %time   time; see '--time-format'. Default: $TIME_FORMAT
+        %log    log string. Default: $LOG_FORMAT
+    -t, --time-format=<string>  set time format; see 'date --help'
+                                or 'man date' for details.
+                                Example: prntl -t '%D %T'
+    -c, --no-color              remove ANSI color codes from log string.
+    -p, --no-print              don't print log to STDOUT.
+    -h, --help                  print this help message and exit.
+    -v, --version               print version and exit.
 EOF
 exit 0
+}
+
+prntl_get_optarg() {
+    if [[ "$1" =~ .+=.+ ]]; then
+        opt="${1%%=*}"; arg="${1#*=}"; sft=1
+    elif [[ ! "$1" =~ .+=$ ]] && \
+         [ "$2" ] && [ "${2:0:1}" != '-' ]
+    then
+        opt="$1"; arg="$2"; sft=2
+    else
+        opt="$1"
+        if [[ "$1" =~ .+=$ ]]; then opt="${1:0: -1}"; fi
+        echo "$0: Missing argument for: $opt" >&2
+        exit 1
+    fi
 }
 
 prntl_log_formatter() {
@@ -64,58 +82,34 @@ fi
 while (( "$#" ))
 do
     case "$1" in
-        -o|--output)
-            if [ "$2" ] && [ ${2:0:1} != '-' ]
-            then
-                LOG_FILE="$2"
-                shift
-            else
-                echo "$0: Missing argument for $1" >&2
-                exit 1
-            fi
-            shift
-            ;;
-        -f|--log-format)
-            if [ "$2" ] && [ ${2:0:1} != '-' ]
-            then
-                LOG_FORMAT="$2"
-                shift
-            else
-                echo "$0: Missing argument for $1" >&2
-                exit 1
-            fi
-            shift
-            ;;
-        -t|--time-format)
-            if [ "$2" ] && [ ${2:0:1} != '-' ]
-            then
-                TIME_FORMAT="$2"
-                shift
-            else
-                echo "$0: Missing argument for $1" >&2
-                exit 1
-            fi
-            shift
-            ;;
+        -o|--output|--output=*)
+            prntl_get_optarg "$1" "$2"
+            LOG_FILE="$arg"
+            shift "$sft";;
+        -f|--log-format|--log-format=*)
+            prntl_get_optarg "$1" "$2"
+            LOG_FORMAT="$arg"
+            shift "$sft";;
+        -t|--time-format|--time-format=*)
+            prntl_get_optarg "$1" "$2"
+            TIME_FORMAT="$arg"
+            shift "$sft";;
         -c|--no-color)
             REMOVE_COLORS=1
-            shift
-            ;;
+            shift;;
         -p|--no-print)
             NO_PRINT=1
-            shift
-            ;;
+            shift;;
         -h|--help)
-            prntl_print_help
-            ;;
+            prntl_print_help;;
+        -v|--version)
+            echo "prntl v$prntl_version"; exit 0;;
         -*)
             echo -e "$0: Unknown option: $1\nSee 'prntl --help'." >&2
-            exit 1
-            ;;
+            exit 1;;
         *)
             LOG+="$1 "
-            shift
-            ;;
+            shift;;
     esac
 done
 
diff --git a/rng b/rng
--- a/rng
+++ b/rng
@@ -7,42 +7,59 @@
 #
 ####################################################
 
+rng_version=0.4
+
 # Default delimiters.
 DEL='\n'
 LDEL='\n'
 
 rng_print_help() {
 cat <<EOF
-Expand ranges like "1-10" into a number series.
+Expand ranges like "1-4,7,9-12" into a number series.
 
-Usage:
-    rng [OPTIONS]... [ARGUMENTS]...
+Usage: rng [-v | --version] [-h | --help] [-d <value>] [-l <value>]
+           [-D | --delimiter=<value>] [<string>]
 
 Options:
-    -d        digits delimiter. Default: '\n'.
-    -l        lines delimiter. Default: '\n'.
-    -D        Set same delimiters for digits and lines.
-    --help    print this help message and exit.
-
-Example:
-   $ rng 1-4,7,9-12 -D ' '
-   1 2 3 4 7 9 10 11 12
+    -d <value>               digits delimiter. Default: '\n'.
+    -l <value>               lines delimiter. Default: '\n'.
+    -D, --delimiter=<value>  Set same delimiters for digits and lines.
+    -h, --help               print this help message and exit.
+    -v, --version            print version and exit.
 EOF
 exit 0
 }
 
-rng_expand() {
-    if [ "$1" ]
+rng_get_optarg() {
+    if [[ "$1" =~ .+=.+ ]]; then
+        opt="${1%%=*}"; arg="${1#*=}"; sft=1
+    elif [[ ! "$1" =~ .+=$ ]] && \
+         [ "$2" ] && [ "${2:0:1}" != '-' ]
     then
-        STR="$1"
+        opt="$1"; arg="$2"; sft=2
     else
-        STR="$(cat <&0)"
+        opt="$1"
+        if [[ "$1" =~ .+=$ ]]; then opt="${1:0: -1}"; fi
+        echo "$0: Missing argument for: $opt" >&2
+        exit 1
     fi
+}
 
+rng_validate() {
+    if [ $(awk '/([0-9]{1,}\-[0-9]{1,})|([0-9]{1,})/' <<< "$1") ] \
+    && [ ! $(awk '/[a-zA-Z*?.+&^%$#@!/\\=><~:\[\]\(\)]/' <<< "$1") ]
+    then
+        return 0
+    else
+        return 1
+    fi
+}
+
+rng_expand() {
     awk -v del="$DEL" -v ldel="$LDEL" 'BEGIN { RS=","; FS="-"; ORS="" }
     NR > 1 { print ldel }
     NF > 1 { for (i=$1; i<$2; ++i) { print i del } print $2; next }
-    { print $1 }' <<< "${STR:0:-1}"  # Cut trailing comma.
+    { print $1 }' <<< "${1:0:-1}"  # Cut trailing comma.
 }
 
 [[ ! "$@" ]] && [ -t 0 ] && rng_print_help
@@ -51,49 +68,30 @@ while (( "$#" ))
 do
     case "$1" in
         -d)
-            if [ "$2" ] && [ "${2:0:1}" != '-' ]
-            then
-                DEL="$2"
-                shift
-            else
-                echo "$0: Missing argument for $1" >&2
-                exit 1
-            fi
-            shift
-            ;;
+            rng_get_optarg "$1" "$2"
+            DEL="$arg"
+            shift "$sft";;
         -l)
-            if [ "$2" ] && [ "${2:0:1}" != '-' ]
-            then
-                LDEL="$2"
-                shift
-            else
-                echo "$0: Missing argument for $1" >&2
-                exit 1
-            fi
-            shift
-            ;;
-        -D)
-            if [ "$2" ] && [ "${2:0:1}" != '-' ]
-            then
-                DEL="$2"
-                LDEL="$2"
-                shift
-            else
-                echo "$0: Missing argument for $1" >&2
-                exit 1
-            fi
-            shift
-            ;;
-        --help)
-            rng_print_help
-            ;;
+            rng_get_optarg "$1" "$2"
+            LDEL="$arg"
+            shift "$sft";;
+        -D|--delimiter|--delimiter=*)
+            rng_get_optarg "$1" "$2"
+            DEL="$arg"; LDEL="$arg"
+            shift "$sft";;
+        -h|--help)
+            rng_print_help;;
+        -v|--version)
+            echo "rng v$rng_version"; exit 0;;
+        -*)
+            echo "$0: Bad option: $1" >&2; exit 1;;
         *)
-            if [ $(awk '/([0-9]{1,}\-[0-9]{1,})|([0-9]{1,})/' <<< "$1") ] \
-            && [ ! $(awk '/[a-zA-Z*?.+&^%$#@!/\\=><~:\[\]\(\)]/' <<< "$1") ]
-            then
+            #if [ $(awk '/([0-9]{1,}\-[0-9]{1,})|([0-9]{1,})/' <<< "$1") ] \
+            #&& [ ! $(awk '/[a-zA-Z*?.+&^%$#@!/\\=><~:\[\]\(\)]/' <<< "$1") ]
+            if rng_validate "$1"; then
                 ARGS+="$1,"
             else
-                echo "$0: Bad argument: $1" >&2
+                echo -n "$0: Bad argument: $1: " >&2
                 echo 'The argument can contain only digits and -,' >&2
                 exit 1
             fi
@@ -101,5 +99,19 @@ do
             ;;
     esac
 done
+
+if [ ! "$ARGS" ]; then
+    ALL_ARGS="$(cat ${1:-/dev/stdin})"
+    for arg in $ALL_ARGS
+    do
+        if rng_validate "$arg"; then
+            ARGS+="$arg,"
+        else
+            echo -n "$0: Bad argument: $1: " >&2
+            echo 'The argument can contain only digits and -,' >&2
+            exit 1
+        fi
+    done
+fi
 
 rng_expand "$ARGS"
